stages:
  - before_script
  - scan
  - build
  - deploy

before_script:
  - apt-get update && apt-get install -y git
  - git clone https://github.com/jackjozwik/DevSecOps-Framework.git
  - cd DevSecOps-Framework
  - echo "Preparing the environment..."
  - chmod +x ./setup.sh
  - ./setup.sh
  - export PATH=$PATH:/usr/local/bin

scan:
  stage: scan
  script:
    - echo "Running all scans in parallel..."
  parallel:
    matrix:
      - SCAN_TYPE: docker
      - SCAN_TYPE: terraform
      - SCAN_TYPE: k8s
  before_script:
    - case $SCAN_TYPE in
      docker)
        echo "Running Trivy to scan configuration..."
        trivy conf .
        echo "Testing Dockerfile..."
        conftest test -p policy/docker_file.rego docker/
        ;;
      k8s)
        echo "Testing Kubernetes configuration..."
        conftest test -p policy/kubernetes.rego kubernetes/
        ;;
      terraform)
        echo "Executing Terraform planning..."
        terraform plan -out=plan.out
        terraform show -json plan.out > plan.json
        echo "Testing Terraform plan against custom policy..."
        conftest test -p policy/terraform.rego terraform/plan.json
        ;;
        esac

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - echo "docker build -t image:latest ."

deploy:
  stage: deploy
  script:
    - echo "Applying Terraform..."
    - echo "terraform apply"
    - echo "Deploying to Kubernetes..."
    - echo "kubectl apply -f kubernetes/"
